version: '3'
services:
  kafka:
    image: spotify/kafka
    ports:
      - '2181:2181' 
      - '9092:9092'
    environment:
      - TOPICS=test
      - ADVERTISED_HOST=docker-machine ip `docker-machine active`
      - ADVERTISED_PORT=9092
