version: '3.4'

services:
  mqtt:
    image: "eclipse-mosquitto:1.6.9"
    ports: 
        - "1883:1883"
    container_name: mosquitto_mqtt_broker
  openhab:
    image: "openhab/openhab:2.5.2"
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    container_name: openhab
    volumes:
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"